apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://127.0.0.1:9411/api/v2/spans"
  features:
    - name: Resiliency
      enabled: true
    - name: proxy.grpc
      enabled: true